sonar.projectKey=Amari-Lawal_RentokilSelfServiceBackendUni
sonar.organization=amari-lawal
sonar.sources=.
sonar.tests=tests
sonar.python.version=3
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/tests/**, **/migrations/**, main.py
sonar.test.inclusions=**/tests/**
